CREATE OR REPLACE DATABASE CEREZAS;
USE CEREZAS;
CREATE OR REPLACE TABLE PARCELAS(
    ID INTEGER,
    NOMBRE VARCHAR(50),
    M2 INTEGER,
    LOCALIDAD VARCHAR(50),
  	PRIMARY KEY (ID)  
);
CREATE OR REPLACE TABLE ESCANDALLOS(
    FECHA DATE,
    ID_PARCELA INTEGER,
    KG_32 FLOAT,
    KG_30 FLOAT,
    KG_28 FLOAT,
    KG_26 FLOAT,
    KG_24 FLOAT,
    PRIMARY KEY (FECHA),
    FOREIGN KEY (ID_PARCELA) REFERENCES PARCELAS(ID)
);
CREATE OR REPLACE TABLE FITOSANITARIOS(
    ID_PRODUCTO INTEGER,
    NOMBRE VARCHAR(40),
    PRECIO FLOAT,
    PLAZO INTEGER,
    COMPONENTE_ACTIVO VARCHAR(40),
    CANTIDAD_ML INTEGER,
    DOSIS_ML INTEGER,
    PRIMARY KEY (ID_PRODUCTO)
);
CREATE OR REPLACE TABLE CURAS(
	FECHA DATE,
    ID_PARCELA INTEGER,
    PRODUCTO_1 INTEGER,
    PRODUCTO_2 INTEGER,
    PRODUCTO_3 INTEGER,
    PRODUCTO_4 INTEGER,
    PRODUCTO_5 INTEGER,
    PRODUCTO_6 INTEGER,
    PRODUCTO_7 INTEGER,
    PRODUCTO_8 INTEGER,
    LITROS INTEGER,
    PRIMARY KEY (FECHA),
    FOREIGN KEY (ID_PARCELA) REFERENCES PARCELAS(ID),
    FOREIGN KEY (PRODUCTO_1) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_2) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_3) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_4) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_5) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_6) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_7) REFERENCES FITOSANITARIOS(ID_PRODUCTO),
    FOREIGN KEY (PRODUCTO_8) REFERENCES FITOSANITARIOS(ID_PRODUCTO)
);
CREATE OR REPLACE TABLE PRECIOS(
    FECHA DATE,
    PRECIO_32 FLOAT,
    PRECIO_30 FLOAT,
    PRECIO_28 FLOAT,
    PRECIO_26 FLOAT,
    PRECIO_24 FLOAT,
    PRIMARY KEY (FECHA)
);
