CREATE OR REPLACE DATABASE CEREZAS;
USE CEREZAS;
CREATE OR REPLACE TABLE ESCANDALLOS(
    FECHA DATE,
    KG_32 FLOAT,
    KG_30 FLOAT,
    KG_28 FLOAT,
    KG_26 FLOAT,
    KG_24 FLOAT,
    PRIMARY KEY (FECHA)
);
CREATE OR REPLACE TABLE PRECIOS(
    FECHA DATE,
    PRECIO_32 FLOAT,
    PRECIO_30 FLOAT,
    PRECIO_28 FLOAT,
    PRECIO_26 FLOAT,
    PRECIO_24 FLOAT,
    PRIMARY KEY (FECHA)
);

